language:
- node_js
node_js:
- 6.8.x
env:
  global:
  - NODE_ENV=test
install:
- npm install
- bash -c 'echo "SESSION_SECRET="$(openssl rand -hex 64)' >> .env
script:
 - npm run coverage
 - npm run codecov
branches:
  only:
    - master
    - stable
    - develop
