language:
- node_js
node_js:
- 6.2.2
env:
  global:
  # - NODE_ENV=test
install:
- npm install
script:
 - npm run coverage
 - npm run codecov
branches:
  only:
    - master
    - stable
    - develop
